### ISSUE TITLE
Add a way to opt-in to exceptions.

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#107]
Currently we capture errors, tuck them away, and never show them.

https://github.com/infinitered/gluegun/blob/master/packages/gluegun/src/domain/runtime.js#L141

Instead of forcing CLI's to print these with:

```js
const context = await runtime.run()

if (context.error) {
  context.print.error(error.message)
  context.print.debug(context.error)
}
```

Let's add a new builder function called `.rethrowErrorsWhenRunning(true)` that people can opt-into when developing.

**Comment by GantMan** [comment]
don't forget `--dev`

**Comment by skellock** [comment]
That's up to CLI folk to decide, imho.
