### ISSUE TITLE
Default commands have unpruned params

### ISSUE THREAD

**Issue by GantMan** [infinitered/gluegun#123]
> As violent delights have violent ends, so do default commands have unpruned params
> -- Dolores

running `ignite add ui` gives `parameters.first` the value of "default"
![image](https://cloud.githubusercontent.com/assets/997157/21294872/899b3d42-c50d-11e6-997b-ba55f4d73131.png)

This looks like some leakage.

👙 Bikini Bonus:
Would be helpful to have `parameters.last` - which is how I plan on fixing this for futureproof ways.  But I'm not a fan of that method.

**Comment by skellock** [comment]
Ya, I agree, something seems off about parameters.

`parameters` gets rewritten because i'm trying to target the plugin/command.

I'm up for changing this.

**Comment by skellock** [comment]
I think what's bothering me about this is its confusing arguments (things that exist on the command line) with arguments (things that get fed into a command).  I think we can probably clear this up with a conversation.

**Comment by jamonholmgren** [comment]
If we do change this, maybe we should use a different property to stay backwards compatible? Maybe that's a horrible idea but I have `parameters.second` strewn all over my code.

**Comment by skellock** [comment]
This has completely reworked in 2.0
