### ISSUE TITLE
context.template.generate - no file found is completely confusing

### ISSUE THREAD

**Issue by GantMan** [infinitered/gluegun#125]
context.template.generate

https://github.com/infinitered/gluegun/blob/master/packages/gluegun/src/core-extensions/template-extension.js

Gives a replace error if the file was not found - very unfriendly to identify the issue :(

![image](https://cloud.githubusercontent.com/assets/997157/21485018/e40ecdd4-cb61-11e6-939d-428239b2ce67.png)

**Comment by skellock** [comment]
We can add a check here to see if the file exists.

https://github.com/infinitered/gluegun/blob/master/packages/gluegun/src/core-extensions/template-extension.js#L41
