### ISSUE TITLE
context.template.generate - for white label

### ISSUE THREAD

**Issue by GantMan** [infinitered/gluegun#126]
trying to use `context.template.generate` looks for a template folder in the whitelabel's plugin folder, so this cannot transfer to usability to any wrapping CLI

**Comment by skellock** [comment]
It's stored in the `templates` directory.  Just like extensions are in `extensions` and commands are in `commands`.

We can change this if you want something different:

https://github.com/infinitered/gluegun/blob/master/packages/gluegun/src/core-extensions/template-extension.js#L41

**Comment by GantMan** [comment]
the issue is ignite can't use this functionality for a plugin, because it looks for the `ignite/templates` which is not going to have the correct template.   I want `some-ignite-plugin/templates` to be used.  Since I want to wrap this functionality, not rewrite it.

**Comment by skellock** [comment]
![image](https://cloud.githubusercontent.com/assets/68273/21485249/3a722c0a-cb6e-11e6-9b4c-f47b19c60618.png)

It should be reading from the plugin's directory.

It's not?

**Comment by GantMan** [comment]
the plugin is ignite.

**Comment by skellock** [comment]
We should add a way to configure the known template locations.

**Comment by GantMan** [comment]
I want to use this inside ignite here:
https://github.com/infinitered/ignite/blob/vector-icons/packages/ignite/src/plugins/default/extensions/ignite.js#L41-L42
