### ISSUE TITLE
Support --flags

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/gluegun#131]
```
$ ignite --version
```

... doesn't seem to work. We'll need a way to support those flags.

**Comment by skellock** [comment]
The easy way to implement this is inside the cli of ignite.

A nice default would be `--version` will print the `package.json` `version`... and provide an override with this command in the builder.

```js
.version('1.2.3')
```

**Comment by skellock** [comment]
Don't forget that `--flags` [are supported](https://github.com/infinitered/gluegun/blob/master/docs/context-api.md#contextparametersoptions) inside commands.

**Comment by skellock** [comment]
We support this the flags but not printing the version number. That’s up to the host cli to do.
