### ISSUE TITLE
Provide a public API to tell if a command has an issue

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/gluegun#134]
I'd love to have access to this function through GlueGun's API:

https://github.com/infinitered/gluegun/blob/4c549ef948a29dfedddca17c40899befec0f4988/packages/gluegun/src/cli/print-wtf.js#L30-L33

Any way we could make that happen?

**Comment by skellock** [comment]
Yes.  Let's chat.

**Comment by skellock** [comment]
Handled by bubbling up the error in 2.0.  👍
