### ISSUE TITLE
Tokens are passed around explicitly - Not great for adding/removing

### ISSUE THREAD

**Issue by GantMan** [infinitered/gluegun#135]
### Example: 
Take a look at the repetition of a token.  Example `commandDescriptionToken` is repeated quite a bit.  See this:
https://github.com/infinitered/gluegun/search?utf8=%E2%9C%93&q=commandDescriptionToken

Adding new commands therefore takes quite a bit of a stroll along passing props/values.

**Comment by skellock** [comment]
Tokens are gone in 2.0.
