### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#14]

**Comment by skellock** [comment]
Going to hand off to @justinhuskey's team.

**Comment by justinhuskey** [comment]
Thanks man. We've got you covered. More to come @skellock and @GantMan.

**Comment by GantMan** [comment]
This should be closed... as gluegun should not have a logo.

**Comment by skellock** [comment]
![image](https://user-images.githubusercontent.com/68273/30256979-a3214bbc-967c-11e7-96f7-f2e56e23af3b.png)
