### ISSUE TITLE
Expose the command list as data

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#148]
Currently printCommands both collects the displays the data.

https://github.com/infinitered/gluegun/blob/master/src/utils/cli/print-commands.js

Which sucks if someone wants to customize that list themselves.

Let's bust these apart and make the data available to DIY printing.

**Comment by jamonholmgren** [comment]
Going to push this one beyond 2.0.0.

**Comment by jamonholmgren** [comment]
Just kidding.
