### ISSUE TITLE
Patching Extension

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#155]
I think it's time for `context.patching` to be a thing.  @GantMan and @jamonholmgren both are using this and have various rounds of iterations in Ignite.

It's useful and I should beg them to add it.

**Comment by jamonholmgren** [comment]
Correct. [This](https://github.com/infinitered/ignite/blob/d2c1842a67873758ed067a9b89f0a78ce0e1dc83/packages/ignite-cli/src/extensions/ignite/patchInFile.js#L3-L53) is a good place to start. API needs to be discussed though, there are a few things that should be ping-pong'd a bit before we land there.

**Comment by jamonholmgren** [comment]
Actually, screw it, I'll do this.

**Comment by jamonholmgren** [comment]
Still planning to do this. Been out of town

**Comment by jamonholmgren** [comment]
Addition to patching extension:

```javascript
context.patching.update('file.json', (config) => {
  config['key'] = 'new value'
  return config
})

context.patching.update('file.txt', (data) => {
  data.replace('Jamon', 'Boss')
  return data
})
```

This will detect the file extension and if it's json, provides an object, otherwise provides a string. Then you return that object or string and it'll get written to disk.

**Comment by skellock** [comment]
Love it.  

Same thing with `ramda` lovin:

```js
const { assoc, replace } = require('ramda')
context.patching.update('file.json', assoc('key', 'new value'))
context.patching.update('file.txt', replace('Hugo, 'Boss'))
```

**Comment by jamonholmgren** [comment]
Made some progress on this tonight, @skellock .

https://github.com/infinitered/gluegun/commit/09b64d59a4982aee09eef71811828318a3a127f0

Tests pass.
