### ISSUE TITLE
Setup Slack Or Gitter

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#16]

**Comment by skellock** [comment]
Maybe a channel in Infinite Red?  I'm not sure how that works.  @twerth might have some insight into this.  I'd be ok with slumming it on gitter too.  Just don't make me use anyroom.

**Comment by twerth** [comment]
I prefer slack TBH.

**Comment by twerth** [comment]
@jamonholmgren ^ thoughts

**Comment by skellock** [comment]
We went slack.  And all is right in the world.
