### ISSUE TITLE
Switch out ascii-table

### ISSUE THREAD

**Issue by GantMan** [infinitered/gluegun#207]
Looks like there's a better table lib that would handle colors:

https://github.com/gajus/table

**Comment by skellock** [comment]
I'm using [cli-table2](https://github.com/jamestalmage/cli-table2).  Works well.  At a glance, the features seem similar.  Word wrapping, color stripping, and alignment is what I was looking for.

Have you used `table`?  How is it?  Any problems?

**Comment by GantMan** [comment]
have not used it, but the streaming feature looks badass

**Comment by skellock** [comment]
I saw the gif, but I must be missing something about the streaming.

Lemme know how it goes if you end up using it.  If it's great, maybe you'd be up for making a plugin.

**Comment by GantMan** [comment]
Gotcha.  What's the upper bound cost for a swap, should I shop other table creators?  Or even construct it myself (it doesn't seem hard honestly).

**Comment by jamonholmgren** [comment]
Closed in #280.
