### ISSUE TITLE
Missing static spinner export

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#208]
https://github.com/infinitered/gluegun/blob/master/packages/gluegun/src/index.js#L36

I didn't export the `print` extension like the others, so I'm missing out on the spinner, sadly.

A non-breaking change to repair this would be to export the spinner manually?  Or maybe take a closer look at the interfaces between the `print` extension and the `utils/print`.

It'd be nice to access it like how we would via `context`.

```
import { print } from 'gluegun'
const { spin } = print
```

Oops.

**Comment by ekryski** [comment]
I'm working on this right now. Just about done.
