### ISSUE TITLE
Support for Node LTS

### ISSUE THREAD

**Issue by iMagdy** [infinitered/gluegun#226]
Why pinning `isNewEnough` to a version that's equal to or greater than `7.6.0`?

Many people use the latest stable LTS version of node in production, currently `6.11.3`. 

What about?

1. [GET](https://nodejs.org/dist/) the latest LTS version, and then use `>=` against it.
2. [Hardcode](https://github.com/infinitered/gluegun/blob/master/packages/gluegun/sniff.js#L7) `6.11.3` instead of `7.6.0` and then regularly update whenever a new LTS version is out.

Thoughts?

If it makes sense, I can PR this.

**Comment by skellock** [comment]
It's because we use `async/await` and I didn't want to make a compilation step such as babel/typescript a requirement.

I like the idea of supporting LTS though.  Do you know of a solution to deal with async/await without converting everything to promises?

**Comment by iMagdy** [comment]
Not sure if promise-less solution & I think converting everything into promises is a major refactoring. 

It's totally fine in my opinion to keep the codebase as is, use Babel, and add a build step. It'll only be necessary during development.

**Comment by jamonholmgren** [comment]
I understand the desire to support 6.11, but I am very loath to add a build step into this process. It's really easy to work on Gluegun right now, since you don't need anything running in the terminal to make changes and test them. Adding a build step & watcher adds more friction than I'm comfortable with.

**Comment by skellock** [comment]
We could use typescript to down level it at publish time. Then store that version as `gluegun/compat` . This would be invisible to the current dev experience. It would also be opt-in by people.

My preference would be typescript to achieve this, not Babel though.

**Comment by skellock** [comment]
And then up the version requirement of the current gluegun from 7.6 to 8.6. 😈 

Actually I’m not even joking.

8.6 gives property spreads.

**Comment by jamonholmgren** [comment]
TypeScript gives enough advantages that it would be more likely to be worth the build step. I'm on board with this.

**Comment by GantMan** [comment]
Looks like we'll be getting LTS this month!!!!
![image](https://user-images.githubusercontent.com/997157/31394346-b250926c-ada3-11e7-9257-09b91db2196a.png)

**Comment by skellock** [comment]
This is great news!  I'm going to close up on this ticket since doing nothing gets us this for free shortly.
