### ISSUE TITLE
Support json config

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#229]
Currently the built in config system only supports `toml`. Let’s add `json` as 1st class.

**Comment by Faultless** [comment]
Hello. Is this related to the `toml.parse` part in `Builder.js`?
I haven't dived much into the code to check how the config file is being parsed and used.

**Comment by skellock** [comment]
Ya.  It starts [there](https://github.com/infinitered/gluegun/blob/master/packages/gluegun/src/domain/builder.js#L35).

It's also [here as well](https://github.com/infinitered/gluegun/blob/master/packages/gluegun/src/loaders/toml-plugin-loader.js#L83).

The idea is, after everything is up & running, you have 1 object, living on the context object, called `config` which contains:

* defaults from all plugins
* overridden by any defaults from the `.toml` config file from the cli
* overridden by any defaults from the user's config file.

This particular issue is, we're using `toml` for that configuration (as well as plugins), but `json` feels like a better fit for `javascript` CLIs.

**Comment by skellock** [comment]
Also, we'll probably make `.json` apply to loading plugins as well.  Which means `toml-plugin-loader.js` is likely getting a change too.

**Comment by jamonholmgren** [comment]
Closing in favor of #282. @skellock, do you feel we should keep TOML support, or drop it in favor of CosmicConfig altogether?

**Comment by skellock** [comment]
Nah... it didnt take off like I’d hoped. Feel free to detomilify.
