### ISSUE TITLE
Provide Mount-points for common CLI - Help, Version etc.

### ISSUE THREAD

**Issue by GantMan** [infinitered/gluegun#243]
In gluegun 2.0 let's handle the common CLI options in a classy way.

## 98% of CLIs
If you want the built-in support, you can just use `commonCommands` function.
![image](https://user-images.githubusercontent.com/997157/31318887-c99239f2-ac1e-11e7-978f-3da331fb8c0c.png)
Maybe even more succinct as `.commonCommands(['help', 'version'])`
These will stop the copy-pasta mess which is mandatory, but not the focus of most CLIs.  You can offload it to us.

## BUT! What if they want to write their own?
**No problem!**, we'll also support `.help()` and `.version()` of every common command, where a user could inject their own function, so they could do something complex like, spit out 2 versions (I'm looking at you `react-native-cli`).  Or simply take control of how things should be displayed.

## No thanks Gluegun, you're getting in my way!!!
**No problem!**, don't use either of the aforementioned functions and just _you do you_.
![giphy-downsized](https://user-images.githubusercontent.com/997157/31319037-963494a8-ac21-11e7-8d71-f40a28625e4f.gif)

----

Common Commands Should Include `['version', 'help', 'silent']`

**Comment by GantMan** [comment]
I've begun the branch for this.  I'll need help from either @jamonholmgren or @skellock to officially know what's the best way to proceed.

Brach Progress:
https://github.com/infinitered/gluegun/tree/feature/commonCommands

**Comment by skellock** [comment]
I’d love for this fluent api interface to be:

```js
  .help()
  .version()
  .silent()
```

The absence of any would mean they are disabled.

The presence of them without params would mean they get defaults.

Passing stuff would allow us to customize their behaviour.

**Comment by GantMan** [comment]
I like it.

**Comment by skellock** [comment]
i like you.
