### ISSUE TITLE
Unable to put tests in commands folder

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#247]
Using `gluegun@2.0.0-alpha.2`, I'm unable to keep this file: `commands/tests/list-stacks.test.ts`.  It is trying to load it as a command.

Here's my runtime config.

```ts

const LOAD_OPTIONS: GluegunLoadOptions = { commandFilePattern: '*.{js,ts}' }

/**
 * Sets up the runtime by configuring gluegun.
 */
export function configureRuntime() {
  return build()
    .brand(BRAND)
    .src(resolve(__dirname, '..'), LOAD_OPTIONS)
    .plugin(resolve(`${filesystem.cwd()}`, BRAND), LOAD_OPTIONS)
    .plugins(`~/.${BRAND}/plugins`, LOAD_OPTIONS)
    .create()
}

```

It probably has to do with `LOAD_OPTIONS`.  I'm using `ts-node` and passing in non-standard a `commandFilePattern`.

**Comment by skellock** [comment]
Here's the issue:

https://github.com/infinitered/gluegun/blob/1cf8014eff543d8996f41a09b72d8f9829576242/packages/gluegun/src/loaders/toml-plugin-loader.js#L59

It'd be nice to remove that opinion and override that.

**Comment by jamonholmgren** [comment]
Idea:

```js
const LOAD_OPTIONS: GluegunLoadOptions = { commandFilePattern: '*.{js,ts}', excludeFilePattern: '*.test.{js,ts}' }
```

**Comment by skellock** [comment]
Sure.  

Another option could be for me to learn how glob patterns work and add a negate pattern. 😆 

And another option could be to gracefully ignore files that aren’t commands when we try to load them.

And another option could be to tell people to not include things that aren’t commands in that directory.

I’m cool with all of the above.

Probably like yours the best.

**Comment by jamonholmgren** [comment]
Went with your first alternate option, which ended up being easier than I expected.
