### ISSUE TITLE
Failing build on semaphore with strange error

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#255]
The `master` branch is failing right now.  Seems really odd.  Is this a semaphore issue?

Let's take a look.

**Comment by jamonholmgren** [comment]
Semaphore hasn't failed since Sunday. Probably a Semaphore glitch. I'll close for now (re-open if we hit this again).

![image](https://user-images.githubusercontent.com/1479215/32067061-b4bef8b4-ba36-11e7-9288-f7c189642944.png)
