### ISSUE TITLE
`gluegun help` on Windows

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/gluegun#263]
Currently outputs:

```bash
GlueGun CLI


```

**Comment by jamonholmgren** [comment]
Interesting, not sure what's going on here. Should be:

```
GlueGun CLI

  generate (g)      -
  generate help     -
  gluegun           Run the gluegun CLI
  help (h)          Displays this help
  new (n, create)   Creates a new gluegun cli
```

**Comment by jamonholmgren** [comment]
@kevinvangelder I think #298 might fix this. Maybe you can test it when it’s out.

**Comment by jamonholmgren** [comment]
![capture](https://user-images.githubusercontent.com/1479215/36116926-dcf9b330-0fec-11e8-8745-369f92aaa531.PNG)

Verified works with latest beta.
