### ISSUE TITLE
Deprecation warning about prompt-text

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#268]
One of our dependencies ([enquirer](https://github.com/enquirer/enquirer)) has a deprecated dependency `prompt-text`.  This appears to be replaced by [prompt-input](https://github.com/enquirer/prompt-input) however their [package.json](https://github.com/enquirer/enquirer/blob/master/package.json#L37) hasn't been updated yet.

It causes this warning when we install `gluegun`.

![image](https://user-images.githubusercontent.com/68273/32421055-3db2cafa-c262-11e7-85eb-89db2176b015.png)

I [submitted a PR](https://github.com/enquirer/enquirer/pull/21), but I'm not convinced I did it right as it's failing their CI. 

Their test suite passes on my machine, `gluegun`'s passes, and a sample gluegun generated CLI is able to do text prompts properly.

I'll update this with news once i get some.

I pushed our branch with these changes up on [`fix-deprecation-warning`](https://github.com/infinitered/gluegun/compare/fix-deprecation-warning?expand=1).

**Comment by jamonholmgren** [comment]
Fixed in #325 .
