### ISSUE TITLE
await an async file read with jetpack?

### ISSUE THREAD

**Issue by GantMan** [infinitered/gluegun#271]
No reason to use async and then await it.

https://github.com/infinitered/gluegun/blob/a9ed51fdffd944ad548e790660ddba5686708e97/src/core-extensions/patching-extension.js#L34

just use `read` which is sync.  Don't add complexity.

**Comment by skellock** [comment]
PR's accepted ;P

**Comment by skellock** [comment]
Agreed.  PR?

**Comment by skellock** [comment]
That was me?

**Comment by skellock** [comment]
Woah, github is having some issues.

So ya, I was the last to edit that code.  Totally missed that.  Fixed up.

**Comment by GantMan** [comment]
LOL, you had a full conversation with yourself and fixed the code.   BTW I would have taken care of this, just filed the ticket so it's noted 😆
