### ISSUE TITLE
Command not found should fail more gracefully

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/gluegun#276]
Steps to replicate:

Create a command folder structure like this:

![image](https://user-images.githubusercontent.com/1479215/32983783-3753a43a-cc4f-11e7-8a93-d8024d9b83b1.png)

Then run `mycli logo`. Fails with an error like this:

```
(node:50164) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error: Couldn't load command help -- needs a "run" property with a function.
(node:50164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The error is there, but buried in unhandled promise errors.

Here is a good starting point: https://github.com/infinitered/gluegun/blob/master/src/loaders/command-loader.js#L42

**Comment by skellock** [comment]
Woah, i had tagged the wrong issue on that pr.  💩
