### ISSUE TITLE
Create a default command that shows help

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/gluegun#277]
All we need is a template command with the same name as the cli that load the help command:

```
// src/commands/mycli.js
module.exports = require('./help')
```

**Comment by GantMan** [comment]
This based off the convo in https://github.com/infinitered/gluegun/issues/243?

**Comment by jamonholmgren** [comment]
@GantMan No, that's different. In this case we just need to update the generated template to include a file by the name of the CLI that is being generated + `.ts|js` and add that line of code.
