### ISSUE TITLE
Configuration Via CosmicConfig

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#282]
I'm seeing a few repos switching over to this style of configuration.  `prettier` and `lint-staged` and a few others.

I'd like to as well with `gluegun`.  Mainly cuz I'd like to use this for the `gluegun`-based CLIs.

The primary benefit is that it supports many different styles & formats of configuration... including @jamonholmgren  and @skellock's favorites:  right inside your `package.json`.

Just wanted to open this for discussion here.

https://github.com/davidtheclark/cosmiconfig

**Comment by jamonholmgren** [comment]
I like the idea of cosmiconfig. 👍 

I'm still working on wrapping my mind around where a configuration file is really helpful. I haven't used configs much, myself, so I need to look at use cases and embed the problem domain firmly in my mind.

**Comment by skellock** [comment]
Many cli's have config files such as `.babelrc`, `.prettierrc`, `webpack.config.js`, `rn-cli.config.js`, etc. `solidarity` and `ignite` both have configs.

Gluegun doesn't need one, but the things people build currently do.

Presently the way it works is via a `.toml` file named after the brand.  I've got a mechanism where the plugins of the cli being built can set their own defaults in their own directory, and they get merged together and overwritten by any users.

This allows the cli's plugin authors to participate in this configuration.

It's be nice if we could move that mechanism wholesale into `package.json`. =)

**Comment by jamonholmgren** [comment]
That makes a lot of sense. This will take me a while to come up with something, but I'll work on it.
