### ISSUE TITLE
Parameters parsing regression

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#288]
I'm having some issues with the parameter parsing in gluegun 2.

With a newly gluegunned project off of `gluegun@2.0.0-alpha.16`, I'm experiencing this:

###  ✅ Command only

```sh
bin/omgparams generate
```

Out of the box, a command by itself is good.

```js
{
  plugin: 'omgparams',
  command: 'generate',
  first: undefined,
  second: undefined,
  third: undefined,
  raw: '',
  string: '',
  array: [],
  options: {},
  argv: ['generate'],
}
```

> HEADS UP: I'm going to remove everything that's `undefined`, `''`, `[]` or `{}` from here on in. It'll be easier to read. They're still there though. Just noise right now.

###  ✅ Alias version

```sh
bin/omgparams g
```

Aliases work as well.

```js
{
  plugin: 'omgparams',
  command: 'generate',
  argv: ['g'],
}
```

###  ✅ Additional parameters

```sh
bin/omgparams generate pizza
```

Even additional parameters work as expected.

```js
{
  plugin: 'omgparams',
  command: 'generate',
  first: 'pizza',
  raw: 'pizza',
  string: 'pizza',
  array: ['pizza'],
  argv: ['generate', 'pizza'],
}
```

### ❌ Options Last

```sh
bin/omgparams generate pizza --now
```

Here's the first problem, when I use options.

The options are leaking into:
 * `second`
 * `string`
 * `array`

(I'm not sure about `raw`.)

```js
{
  plugin: 'omgparams',
  command: 'generate',
  first: 'pizza',
  second: '--now',
  raw: 'pizza --now',
  string: 'pizza --now',
  array: ['pizza', '--now'],
  options: { now: true },
  argv: ['generate', 'pizza', '--now'],
}
```

### ❌ Options First

```sh
bin/omgparams --now generate pizza
```

If i put the --now first, it pushes:

* `generate` into `first`
* `pizza` into `second`

```js
{
  plugin: 'omgparams',
  command: 'generate',
  first: 'generate',
  second: 'pizza',
  raw: 'generate pizza',
  string: 'generate pizza',
  array: ['generate', 'pizza'],
  options: { now: 'generate' },
  argv: ['--now', 'generate', 'pizza'],
}
```

It looks as if `options` are being processed, when they should be lifted out entirely before we start investigating what's left.  This is what `minimist` does for us.

Any thoughts or pointers?

**Comment by skellock** [comment]
Potential workaround:

When you call `.run()` from your app, you can inject in a pre-processed version:

```ts
import * as minimist from 'minimist'
const commandLine = minimist(argv.slice(2))
// the call to `.run` with arguments for now
await runtime.run(commandLine._, omit(['_'], commandLine))
```

This seems to bypass the issue.

I think the issue is around here.  We shouldn't be reading directly from `process.argv`, but rather a minimist-preprocessed version of what it calls `_`.  This is what's left after it strips down all option flags.

https://github.com/infinitered/gluegun/blob/ef4222c0d251477d5b1b3f118e7759c1ef8ab1c5/src/domain/runtime.js#L64

**Comment by jamonholmgren** [comment]
Thanks for the really detailed report, Steve. Agree with your assessment. I'll think through the implications when I'm back in town and post my thoughts.
