### ISSUE TITLE
Jest watch mode vs unhandledRejections

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#295]
This [code](https://github.com/infinitered/gluegun/blob/master/src/index.js#L23-L26) is causing jest to throw errors.

```js
process.on('unhandledRejection', up => {
  throw up
})
```

In watch-mode, jest does this:

```
(node:19470) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit
```

How would you feel about having the ability to opt in to this?

`.rethrowUnhandledRejections()` 

Or something equally unwieldly?

**Comment by jamonholmgren** [comment]
I can fix that particular issue (see #297) and will think about the config option to rethrow -- I'd rather not, if we can avoid it, at least for now.
