### ISSUE TITLE
Convert gluegun source to TypeScript

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/gluegun#306]
I'm about 80% through [a major refactor](https://github.com/infinitered/gluegun/compare/refactor/internals), which includes converting over to TypeScript. So I'm filing this issue to track some of the items.

1. I'm using `ts-node` right now, and it works pretty well. However, my assumption is that we should keep this as a devDependency and compile a JS bundle ... when other CLIs import `gluegun`, they get the JS bundle. Is that right, or can we assume `ts-node` as a full dependency and call it good?
2. If we do compile a JS bundle, we lose some of the debugging capability in the wild, because we won't get reasonable line numbers.
3. If we do compile, we could conceivably target/support older versions of node. Should we?

**Comment by skellock** [comment]
1. Yes, you are right. 

`ts-node` is great for dev but not for shipping. TypeScript isn’t really a bundler so it won’t pack up dependencies. It just turns our source into a different source. There will be a build step required for shipping. Add `outDir: dist` to the `tsconfig.json` (for example) then run `tsc -p .` and we’re done.

2.  Source maps is how you fix this. 

`sourceMaps: true` in our config will emit these. With the right `target` setting, the output of ts is remarkably human.  Not like Babel. In practice this isn’t a big deal. Being a superset of js is an advantage here.  🥇 

3. Yes and yes! Allowing people to opt-in to dependencies is the right way (albeit a little more work).

I also recommend going the bundle route on top of all this. Multi-format would be great to give more flexibility to our downstream. `rollup` can do all of this. And providing instructions to clis on how to do this too would be way above & beyond. 🏆

**Comment by GantMan** [comment]
Supporting older versions of NODE!?  Woah!  epic!

**Comment by jamonholmgren** [comment]
So this is somewhat easier said than done, after battling it a bit. I think we should keep it at Node 7.6+ until someone really wants prior Node version support. I have an idea the direction I'd need to go to support it, but I'm just not too keen on fighting it at the moment, especially with Node marching onward and onward.

**Comment by skellock** [comment]
What problem did you run into?  TS supports this out of the box by setting the appropriate target.

**Comment by GantMan** [comment]
I too am interested.  It seems it should be straightforward once you have TypeScript to simply ship to older JS in the compile.

**Comment by jamonholmgren** [comment]
It's not the library code itself, but rather the `gluegun` CLI and any `gluegun new` generated CLI. I can remove or lower the Node requirement in the library and it'll probably work, because I'm targeting `es5` right now for that bundle. But you'd need to change your own CLI to properly work with es5 as well. I could make some sort of `--target=es5` flag on new CLIs and also make the gluegun CLI itself es5 compatible. Doable, not super hard, but not really a priority right now for me.
