### ISSUE TITLE
Prefer `import` over `require`

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#310]
I recommend sticking with `import` rather than [`require`](https://github.com/infinitered/gluegun/blob/0e368e24fdc0a80d0098dc1a6bf5750db8893d88/src/index.ts#L24-L30) as much as possible to keep the types.

`require` does have it's place for sure though.  Such as, guarding with an `if` statement or intentionally dodging bad types in a 3rd party lib.  Unlike `require`, `import` gets hoisted so it's not as flexible, but checks that huge static analysis checkbox!

**Comment by jamonholmgren** [comment]
I did try to avoid `require` wherever I could. However, in some cases we're loading things dynamically and need to. I'll make another pass through and see if I missed some `import` opportunities.

**Comment by skellock** [comment]
Hey, something I learned this morning.  

I was wrong about import being hoisted.

`import` doesn't get hoisted in node.js & typescript.  I found that out by doing `require` mocks in `jest` **before** `imports`.  

It does in ReactNative though... that narrows it down to babel and metro bundler.

Suffice to say, this entire toolchain is pure comedy. 😆

**Comment by jamonholmgren** [comment]
Wow. I feel like I need to write up a blog post about all this. But it's rather daunting, because there are so many use cases and tools at play here.

### Environments

* Node
* Electron
* Browsers (modern and antique)
* React Native

### Tooling

* Straight ES5
* Straight ES6+
* Running with TS-Node
* Compiling with TSC
* Compiling with Babel
* Rollup

This is a very incomplete list and it's already pretty crazy.

**Comment by skellock** [comment]
and mjs, system, commonjs

React Native's module resolution is all kinds of crazy (haste). Facebook has their own way of resolving modules that works for their scale.

Then there's the special package.json overrides for `browser`, `jsnext:main`, `react-native` where you can both specify a different entry point and/or swap individual modules (not official spec)?

Then there's async imports people are using for code spitting.

**Comment by skellock** [comment]
We've spent the last 10 years (and probably the next 5) reinventing something that's been solved for 30 years.  Static & dynamic library loading.

I love learning, so I'm not bitter. I'm just unproductive.

**Comment by jamonholmgren** [comment]
Very relevant: https://gist.github.com/ceejbot/b49f8789b2ab6b09548ccb72813a1054
