### ISSUE TITLE
Re-exporting

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#311]
Instead of [importing just to export](https://github.com/infinitered/gluegun/blob/0e368e24fdc0a80d0098dc1a6bf5750db8893d88/src/toolbox/string-tools.ts#L1-L17), you can do that in one step by changing the first word from `import` to `export`.

```ts
export * as camelCase from 'lodash.camelcase'
```

**Comment by jamonholmgren** [comment]
Nice! I think my problem was I tried to do `export cameCase from 'lodash.camelcase'` which didn't work. womp womp

**Comment by jamonholmgren** [comment]
So `export * as whut from 'whut'` isn't supported right now, although there are a [couple](https://tc39.github.io/proposal-export-ns-from/) [proposals](https://tc39.github.io/proposal-export-default-from/) currently hanging out in stage 1.

I *may* be able to simplify the syntax somewhat though.

**Comment by skellock** [comment]
I must have gotten it confused with `export * from 'whut'`.  😭 

I'm sad.
