### ISSUE TITLE
Clean up `findCommand` type definition

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#317]
I find [inline on-the-fly typings](https://github.com/infinitered/gluegun/blob/0e368e24fdc0a80d0098dc1a6bf5750db8893d88/src/runtime/runtime-find-command.ts#L19) pretty hard to read.

If you felt like really typing it, maybe something like this:

```ts
export interface FindCommandResult {
  plugin?: Plugin
  command? Command
  array: string[]
}
```

Since this is not an interface a user will be working with (only consuming from this spot), I'd actually just delete the typing entirely and let TypeScript infer it.

You may have to change your inbound argument `parameters: any` to `parameters?: string[]` though.

**Comment by jamonholmgren** [comment]
Good call. 👍

**Comment by jamonholmgren** [comment]
Even better, I already have an exported type for `RuntimeParameters`. 👍
