### ISSUE TITLE
Switch to `minimist2`

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/gluegun#328]
Per [this comment](https://github.com/substack/minimist/issues/115#issuecomment-357537064), @berdon has created a TypeScript rewrite of minimist, called [minimist2](https://github.com/berdon/minimist2). Given that the original minimist isn't really being maintained anymore, it might make sense to switch to the new library.

**Comment by wuweiweiwu** [comment]
@jamonholmgren Can I work on this?

**Comment by jamonholmgren** [comment]
@wuweiweiwu Certainly, thanks for offering!

**Comment by wuweiweiwu** [comment]
@jamonholmgren I am probably misunderstanding but it seemed that minimist is not a direct dependency of gluegun but is a dependency of dependencies. So to change that, wouldn't it require changing it in the dependencies' dependencies?

**Comment by jamonholmgren** [comment]
@wuweiweiwu You're right. We [recently switched](https://github.com/infinitered/gluegun/pull/294) to `yargs-parser` because `minimist` isn't being maintained anymore, anyway. I had forgotten I did that. 🤦‍♂️
