### ISSUE TITLE
Two circular dependencies

### ISSUE THREAD

**Issue by GantMan** [infinitered/gluegun#334]
Not that they are bad, but they smell like possible o crap mistakes.

`run-context.ts` imports `command.ts` and vice versa.  It's via a function, but still not immune.

Also a more complex circular dependency:
`run-context.ts -> plugin.ts -> extensions.ts -> run-context.ts`

It's worth checking if we can properly structure the code so there could be no chance of a circular dependency.

**Comment by jamonholmgren** [comment]
Defining the types in a single file like @skellock likes to do would help with this.

I'm not going to be able to get to Gluegun for at least a week, perhaps two. My plate is pretty full at work for a while.

**Comment by jamonholmgren** [comment]
@GantMan Does this actually cause any issues in practice?

**Comment by GantMan** [comment]
hypothetically it could.  Just means you **could** cause an issue.  Like if you set those up to be interdependent and then serialized the data you'd have an outrageous bug to find.

**Comment by skellock** [comment]
The relationship from Command to RunContext is interface only, not data, so it wouldn’t cause any runtime issues like serialization problems.

Same with the plugin/extension gauntlet.  Ownership is only 1 way, even though the interfaces are in both spots.

I love how TypeScript knows what to do.

**Comment by jamonholmgren** [comment]
I'm going to call this one `wontfix` ... but feel free to bring it up again if we run into any issues!
