### ISSUE TITLE
Support `export default` as well as just `module.export =`

### ISSUE THREAD

**Issue by orta** [infinitered/gluegun#337]
I've never wrote a `module.export =` before, so I figured it was just the same as `export default`. Turns out it wasn't the same 💯

**Comment by jamonholmgren** [comment]
I just saw that TypeScript _does_ support dynamic imports:

https://blog.mariusschulz.com/2018/01/14/typescript-2-4-dynamic-import-expressions

I'm going to look into this ASAP.

**Comment by skellock** [comment]
Maybe [here](https://github.com/infinitered/gluegun/blob/master/src/loaders/command-loader.ts#L47) we could be a little more permissive to check for `default` as well?

**Comment by jamonholmgren** [comment]
Closed via #343.
