### ISSUE TITLE
Support async plugins / extensions

### ISSUE THREAD

**Issue by orta** [infinitered/gluegun#340]
Code I'd like to write:

```ts
import { ghauth } from "../util/promised_ghauth"
import { Context } from "../context"

const setGithubCredentials = async (context: Context) => {
  context.githubAuth = await ghauth()
}

module.exports = setGithubCredentials
```

and 

```ts
import { getSettings } from "../util/settings"
import { Context } from "../context"

const setSettings = async (context: Context) => {
  context.settings = await getSettings()
}

module.exports = setSettings
```

The GH Auth prompt does a bunch of pre-requisite work, it's feasible that I can add a function to handle it per-command but it's basically something I want on the first time user flow anyway. 

I took a quick look at this and it seems like it'd add async code everywhere so opted to not PR right now and to move it to a function my command can handle as I only have one ;)

Opened so people can decide if this is something you want

**Comment by orta** [comment]
Yeah the promise might probably be the best option TBH 👍

**Comment by jamonholmgren** [comment]
I'm going to close this issue, given we have a reasonable pattern to follow above. Happy to restart the discussion if anyone has strong feelings about it.

**Comment by RichiCoder1** [comment]
I actually do. Basically:
* We want to ship a default config out of band from local nat accessible services. It be nice to either load this or warn the user their current config is out of date before a command runs.
* General outdated checks.

There was another use cases I though of, but forgot.

It looks like it'd be a simple change, would you take a PR?

**Comment by jamonholmgren** [comment]
I really like the idea of `is-outdated` being built in to Gluegun. Perhaps on `toolbox.meta.outdated()` as an async function?

Regarding your use case, I can see how that would be helpful. Since it won't break backwards compatibility, I'm open to it. ref #449

**Comment by RichiCoder1** [comment]
>I really like the idea of is-outdated being built in to Gluegun. Perhaps on toolbox.meta.outdated() as an async function?

Indeed! I like it. Though it might also be good to have it on `builder` too.
Something like:
```
// ready
const { build } = require('gluegun')
const package = require('../package.json')

// aim
const movieCLI = build('movie')
  .src(`${__dirname}/core-plugins`)
  .plugins('node_modules', { matching: 'movie-*' })
  .help()
  .version()
  .checkForUpdates(package.name, package.version)
  .defaultCommand()
  .create()

// fire!
movieCLI.run()
```

Probably worth it's own issue.
