### ISSUE TITLE
Adding defaultCommand prevents non-core plugins from working

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#344]
### Problem

Using `gluegun@2.0.0-beta.4`, if you add register a `.defaultCommand()` on your builder, it will prevent from running commands in other plugins.

### Scenario

After adding a `.plugin()`, the `Runtime` shows the 2 plugins.  The first being the default set, the 2nd one being the one I add.

If you try to run it with `mycli plugin2 validcmd` the `.defaultCommand()` runs instead.

You can see it fine, you just can't run it.

### Workaround

Don't use `.defaultCommand()` (unfortunately).

### Where This May Be Happening

I think the problem is in `findCommand` within `src/runtime/runtime-find-command.ts`.

Here's how I think it's going down.

* The [default plugin](https://github.com/infinitered/gluegun/blob/eeb40321305ace72f214a15ab2fe12234dad5a17/src/runtime/runtime-find-command.ts#L25)  is taking precendent.
* [finalCommandPath](https://github.com/infinitered/gluegun/blob/eeb40321305ace72f214a15ab2fe12234dad5a17/src/runtime/runtime-find-command.ts#L39) evals to `[]` because this command doesn't match anything
* We then hit the if statement happy path and [wind up fishing up the default command](https://github.com/infinitered/gluegun/blob/eeb40321305ace72f214a15ab2fe12234dad5a17/src/runtime/runtime-find-command.ts#L66)
* Then we [bail](https://github.com/infinitered/gluegun/blob/eeb40321305ace72f214a15ab2fe12234dad5a17/src/runtime/runtime-find-command.ts#L75) on our `find` because we found it... preventing the loop into our 2nd plugin (where the command really lives).

### Random Thoughts

I wonder if we could do a 2 pass search.  Identify the plugin first, and then search for the command within?

**Comment by jamonholmgren** [comment]
@skellock Good catch. Your analysis is correct. I haven't been super happy with our command resolving anyway.

What I'd like to do is have one `commands` list. We don't loop through plugins and find commands; instead, we just search down one master list. The defaultCommand could be at the end, then, easily.

This will require some rethinking and reworking. I'll try to find a workaround in the meantime.

**Comment by jamonholmgren** [comment]
I've created a failing test for this. Working on a fix.
