### ISSUE TITLE
Rename RunContext to Toolbox

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/gluegun#350]
One thing that I've noticed some new-to-CLI developers trip over is the idea of `context`. It's not immediately obvious what this is, and there's a bit of a learning curve.

I am a big believer that naming things is both _hard_ and extremely _important_, because it influences how people reason about things.

This is what we have currently:

```js
{
  run: async (context) => {
    const { prompt, parameters, filesystem } = context
    context.print.info('hi there')
    // ... do your thang
  }
}
```

While doing the internals refactor in #307, I settled on the concept of a `toolbox` folder (formerly known as `utils`) that had all our sharp knives and screwdrivers. The `core-extensions` are more like drawers full of tools, and those are sourced from `toolbox`.

So far, I've really, really liked this concept -- it's made it easy to reason about what goes where. It also goes with the "gluegun" concept, which is itself a tool.

So, why not just call the `RunContext` a `Toolbox`? It contains all the tools we've added to it via core extensions and plugin extensions.

```js
{
  run: async (toolbox) => {
    const { prompt, parameters, filesystem } = toolbox
    toolbox.print.info('hi there')
    // ... do your thang
  }
}
```

I like the look and feel a lot.

Not only that, but it's backwards-compatible*. If you want to continue to call it a `context`, you can.

* _If you're using TypeScript, you may need to rename `GluegunRunContext` to `GluegunToolbox` in your project_

**Comment by skellock** [comment]
A gluegun is also a tool, so bonus points on being thematic.

This I a breaking change. If you rename that, our builds break. You can alias it though with a deprecation warning in the docs and we’re gold.
