### ISSUE TITLE
TypeScript-generated CLIs should have `npm run build` and Rollup built-in

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/gluegun#361]
When generating a TypeScript CLI, it comes pretty bare-bones. Let's add a build script (for production) as well as a Rollup script that allows for easier distribution on NPM.

**Comment by jthegedus** [comment]
See my suggestion here https://github.com/infinitered/gluegun/issues/287#issuecomment-451796986

**Comment by mikeerickson** [comment]
I will take on this task after wrapping up the command help interface.  Was working on it this weekend, but had some family issues to deal with (our family lab is quite sick ans not looking good)

**Comment by jamonholmgren** [comment]
@mikeerickson I'm so sorry to hear that. I hope it recovers.

**Comment by mikeerickson** [comment]
Unfortunately, we had to put him down Monday morning. Been a somber house this week, he was a huge part of my life and I am broken hearted, such an amazing best friend.

**Comment by jamonholmgren** [comment]
:cry: I'm so sorry Mike. I lost my dog when I was 20, rough time.

**Comment by jamonholmgren** [comment]
Regarding this issue, we can actually close it due to #444 implementing a TypeScript build process.
