### ISSUE TITLE
Change `colors` to `colors/safe`

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/gluegun#363]
Per [this comment](https://github.com/infinitered/gluegun/pull/357#issuecomment-368283970), the `colors` package adds a significant startup penalty. It's possible that we could realize some performance savings by using `colors/safe` instead, which has the added benefit (IMO) of not monkeypatching the string prototype.

https://github.com/Marak/colors.js#using-string-safe-api

This line:

https://github.com/infinitered/gluegun/blob/master/src/toolbox/print-tools.ts#L2

needs to change to

```js
import * as colors from 'colors/safe'
```

When doing this, it would be helpful to measure if this does improve startup time.

This will a backwards-compatible change. It doesn't change any Gluegun-documented API, which is the important part. If someone was relying on the `colors` monkeypatching they'll need to either reintroduce it by doing `require('colors')` or convert to using the Gluegun-documented APIs.

**Comment by Aaron-K-T-Berry** [comment]
I can pick this up 🙂

**Comment by jamonholmgren** [comment]
Yay @Aaron-K-T-Berry !

**Comment by Aaron-K-T-Berry** [comment]
#614 has been closed so I think this issue can be closed now 👍
