### ISSUE TITLE
[QUESTION] Replace a repetitive string with a single `patching.replace`

### ISSUE THREAD

**Issue by donnes** [infinitered/gluegun#374]
I have the string "abracadabra" in multiple lines of a file and I want to replace these strings with a single `patching.replace`. Has a clean way to I do it?

Thanks :D

**Comment by jamonholmgren** [comment]
Hey @donnes , thanks for the question! I've been out of town, just saw this.

Under the hood, `replace` is using the JS string replace.

https://github.com/infinitered/gluegun/blob/master/src/toolbox/patching-tools.ts#L81-L90

```typescript
/**
 * Convenience function for replacing a string in a given file. Async.
 *
 * @param filename       File to be prepended to
 * @param oldContent     String to replace
 * @param newContent     String to write
 */
export async function replace(filename: string, oldContent: string, newContent: string): Promise<string | false> {
  return update(filename, data => (data as string).replace(oldContent, newContent)) as Promise<string | false>
}
```

You can pass in a global regex for the first parameter:

```js
await patching.replace(filename, new Regex('abracadabra', 'g'), 'new content here')
```

If you're using TypeScript, it'll complain that you're not passing in a string for the second parameter. For now, you can override that with `new Regex('abracadabra', 'g') as string`, but we should really add that as a possible parameter type there. If you want to submit a PR, that would be awesome. :)

**Comment by donnes** [comment]
@jamonholmgren No problem about the delay.
Yeah, I'm using Javascript instead of TypeScript and your way works very well. Thanks <3

I'll take a look about regular expression as parameter type and submit a PR when I had some time.

Thanks again and great work with Gluegun/Ignite. :D
