### ISSUE TITLE
Typescript dependencies not found

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/gluegun#382]
As you can see in https://github.com/infinitered/solidarity/pull/202, if the host app doesn't pull in `@types/cli-table2` (and friends), TypeScript won't be able to find them when trying to compile the app. This isn't a great experience.

Our options:

1. Ship those dependencies as `dependencies` not `devDependencies`
2. Copy those types into our own types
3. Require host apps to manually bring in types in their own devDependencies

Related: https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies

**Comment by rmevans9** [comment]
If you export something of a type that is in `@types/cli-table2` I think it would make sense to be in `dependencies` since it is needed for your public API.

**Comment by jamonholmgren** [comment]
@rmevans9 Right, problem is that it means CLIs that don't use TypeScript will also have that dependency, despite not needing it.

**Comment by cmckni3** [comment]
`peerDependencies` or `optionalDependencies`?

**Comment by skellock** [comment]
I'm liking `optionalDependencies`.  That's a wonderful idea.  I never even thought of that.

The clients can opt-in with `devDependencies`.

👍 👍 👍 👍

**Comment by jamonholmgren** [comment]
I hadn't heard about `optionalDependencies` ... [reading into it](https://docs.npmjs.com/files/package.json#optionaldependencies), it appears that it's intended for cases where the dependency might not be available, and allows continuing on if that's the case. Since it'll almost certainly be available, it'll be installed just like `dependencies`.  So that doesn't quite help us.

`peerDependencies` isn't quite right either.

Hm.

**Comment by cmckni3** [comment]
That’s true about `optionalDependencies`. I would use `peerDependencies` so the project can opt in. It’s what I use for Angular stuff even though Angular dependencies are required.

**Comment by jamonholmgren** [comment]
My only worry with that is people getting peer dependency warnings when they're not using TypeScript.

**Comment by cmckni3** [comment]
Yeah although that’s a good thing. I guess I would lean more towards a line in the README for TypeScript users.

**Comment by jamonholmgren** [comment]
We can also add them into the new TypeScript CLI boilerplate.

**Comment by cmckni3** [comment]
Circling back around to this. Since the new cli-table group happened. I believe at some point packaging the types with the project itself was suggested over @types. I can't find that article or the reference in DefinitelyTyped but projects built in TypeScript get this for free.

It appears that https://github.com/cli-table/cli-table3 packages the type definitions in this way.

**Comment by cmckni3** [comment]
I believe this can be closed.
