### ISSUE TITLE
Gluegun not able to parse windows filesystem to execute commands

### ISSUE THREAD

**Issue by kaustavghosh06** [infinitered/gluegun#384]
I have a directory structure like this commands/mycommand/subcommand.js

So ideally when using the gluegun framework, `clibrand mycommand subcommand` my subcommand.js should get invoked. it works fine on my Mac and Unix machine but doesn't get invoked in my windows machine. Is it a filesystem issue which gluegun is not able to comprehend?

**Comment by jamonholmgren** [comment]
Yeah, sounds like there's a filesystem issue. Thanks for reporting!

**Comment by jamonholmgren** [comment]
Closed by #385.

**Comment by kaustavghosh06** [comment]
Thanks @kavengagne. @jamonholmgren Would be great if this could be published to npm.

**Comment by cmckni3** [comment]
I removed the output redirection to `/dev/null` during TypeScript compilation of gluegun. Gluegun should build on Windows.

Maybe ci should be setup for Windows. Can use Azure Pipelines for free with open source projects.

**Comment by kavengagne** [comment]
Azure Pipelines are starting to support Yaml, which is a nice thing!
I agree CI should be setup for Windows to make sure no one breaks it.

**Comment by jamonholmgren** [comment]
I'll publish to NPM, yes.

@cmckni3 Do you think we're good to publish 2.0.0?

**Comment by cmckni3** [comment]
Can't really say since I haven't updated or used gluegun in awhile. Maybe do another beta, update ignite, and get community feedback?

**Comment by jeremyepling** [comment]
I saw that you mentioned Azure Pipelines and I'm a product manager for it. Let me know if you try it and have any questions or suggestions.

**Comment by cmckni3** [comment]
@jeremyepling awesome! I have it setup but working on fixing integration tests on Windows

**Comment by kaustavghosh06** [comment]
@kavengagne This issue doesn't seem to have been solved completely with -> https://github.com/infinitered/gluegun/pull/385 
Was a new version of gluegun published with the above-mentioned PR?

My code structure looks something like this:

cli-core/
  src/
      commands/
           push.js

plugin-1/
   commands/
       subcommand1/
           push.js

So when I run `<core-brand> push` , my cli-core/src/commands/push.js should be executed but instead, plugin-1/commands/subcommand1/push.js gets executed. 

This behavior is just on windows and works perfectly fine on Linux based systems.

**Comment by kavengagne** [comment]
I should have some time to look at that issue soon.

**Comment by cmckni3** [comment]
@kaustavghosh06 a new version was not published to npm.

Apologies, this is tough for me to look into since I use Mac and Linux daily. I use my gaming computer with Windows to diagnose issues when I have time haha.

**Comment by cmckni3** [comment]
@jamonholmgren can you make a release for 2.0.0-beta.12?

**Comment by kaustavghosh06** [comment]
@cmckni3 Would be great if we could get this published. Pretty critical for our CLI..its just crapping out on windows :/  -> https://github.com/aws-amplify/amplify-cli/issues/29

**Comment by jamonholmgren** [comment]
@kaustavghosh06 @cmckni3 I'm working on it now!

**Comment by jamonholmgren** [comment]
![image](https://user-images.githubusercontent.com/1479215/46617797-89e18000-cad2-11e8-8c3f-d4df853c4ee1.png)

beta 12 published! @kaustavghosh06 if this works for you I'm going to cut a 2.0.0 release.

**Comment by jamonholmgren** [comment]
FYI we will be working some more on this soon to fix the remaining reported issues.

**Comment by cmckni3** [comment]
cool, I have a cli project coming up for a data pipeline that needs to work on Windows. Will probably go with gluegun and see how things go.

**Comment by jamonholmgren** [comment]
@kaustavghosh06 I tried to replicate this issue, but it appears that every version of Gluegun since beta 7 works as I'd expect (it runs the plugin code). Is there a way for you to publish a minimal repro for me to clone down to my windows machine and try?

**Comment by kaustavghosh06** [comment]
@jamonholmgren  So the original issue mentioned in this issue is resolved with the subcommands getting invoked. Now there is a new issue which came up because of that change. 
Let me try explaining this out here:

We have our amplify-cli package which is the core package containing the cli.js file with the build() function. Our core package structure looks something like this:

```
amplify-cli
|_commands
   |_push.js
```

And then we have a plugin called amplify-category-storage whose structure is something like this

```
amplify-category-storage
|_commands
  |_storage
     |_push.js
```

So currently, `amplify storage push` works fine but when you execute `amplify push`, that doesn't invoke the function present in the core package -> amplify-cli/commands/push.js but instead invokes the function in the storage plugin -> amplify-category-storage/storage/push.js.

This behavior is only in windows and not in Unix based systems.

**Comment by kaustavghosh06** [comment]
@jamonholmgren Just validated the CLI with the latest version of Gluegun and the above-mentioned issue seems to have been mitigated 👯‍♂️

**Comment by jamonholmgren** [comment]
@kaustavghosh06 Woo hoo! <3
