### ISSUE TITLE
CI should be setup for Windows to avoid breaking support in the future

### ISSUE THREAD

**Issue by kavengagne** [infinitered/gluegun#386]
As mentionned by @cmckni3, CI should be setup for Windows as well.
This would avoid breaking Windows support in the future.

- I can help with the Azure Pipeline setup
- Someone from infinitered would need to
    - Setup the Microsoft account
    - Setup the checks for PRs in github

**Comment by cmckni3** [comment]
I can help as well if InfiniteRed sets up the account.

**Comment by jamonholmgren** [comment]
Nice ... @kevinvangelder , would you lead this from our end?

**Comment by kevinvangelder** [comment]
Azure Pipeline has been added to the project and I've added master branch protection with Semaphore. (We'll add Azure Pipeline once it's been configured).
