### ISSUE TITLE
Better typescript support for dependencies

### ISSUE THREAD

**Issue by wgottschalk** [infinitered/gluegun#393]
I'm going through the tutorial online and I'm not sure if this is a typescript thing or a gluegun thing. What I would like is to be able to define an extension:

```typescript
// src/extensions/imdb-extension.ts

import { prompt } from 'gluegun/prompt'
import * as imdb from 'imdb-api'
import { GluegunToolbox } from 'gluegun'

export interface ImdbExtension {
  imdb: {
    getMovie: (movieName: string) => Promise<imdb.Movie>
  }
}

export default (toolbox: GluegunToolbox) => {
  // memoize the API key once we retrieve it
  // let imdbKey: string | false = false

  // get a movie
  async function getMovie(movieName: string): Promise<imdb.Movie> {
    const result = await prompt.ask({ type: 'input', name: 'key', message: 'API Key>' })
    if (!result.key) return

    return imdb.get({ name: movieName }, { apiKey: result.key, timeout: 30000 })
  }

  // attach our tools to the toolbox
  toolbox.imdb = { getMovie }
}
```

AND I would like this object to show up in my typescript autocompletions. The closest thing I could think of was creating the interface above and doing some gymnastics but I feel that the typesystem could support this natively somehow.

```typescript
import { GluegunCommand, GluegunToolbox } from 'gluegun'
import { ImdbExtension } from '../extensions/imdb-extension'

const movieCommand: GluegunCommand = {
  name: 'movie',
  run: async (toolbox: GluegunToolbox) => {
    // ** Fails - Type 'GluegunToolbox' is not assignable to type 'ImdbExtension'.   Property 'imdb' is missing in type 'GluegunToolbox'. [2322]
    // const { imdb }: ImdbExtension = toolbox 

    // works
    const { imdb }: ImdbExtension = toolbox as any
    const movie = await imdb.getMovie('The Room')
    if (movie.name) toolbox.print.info(movie.name)
  }
}

export default movieCommand
```

What would be ideal
```typescript
const movie = toolbox.imdb.getMovie("The Room")   <- just autocompletes because TS knows the type
if (movie.name) toolbox.print.info(movie.name)
```

**Comment by jamonholmgren** [comment]
@wgottschalk Thanks for the issue, and apologies for how long it's taken me to respond. Here's an example that I think might help you understand how to structure your type:

https://github.com/infinitered/solidarity/blob/master/src/types.ts#L43

@GantMan might have additional thoughts.

**Comment by GantMan** [comment]
Yup @wgottschalk - I would define a new type that fits your CLI bag of tricks, and start it off by extending what comes out of Gluegun.

This way you can define an interface that is explicit in definition of what should and should not exist.  This also keeps you way from every using `any`.

I like defining all my interfaces in a single file, this feels very similar to defining a JSON schema, and provides a clean export for anyone consuming my CLI types.

**Comment by wgottschalk** [comment]
Got it. So I would define a `types.ts` file at my root and I could do something like:
```typescript
interface ImdbExtension {
    getMovie: (movieName: string) => Promise<imdb.Movie>
}

export interface MyApp extends GluegunToolbox {
  imdb: ImdbExtension;
  // more extensions here
}
```
and then I type everything as `MyApp` instead of `GluegunToolbox`.

Would this be worth adding to the docs somewhere? I wouldn't mind adding a paragraph or two in the tutorial.

**Comment by jamonholmgren** [comment]
@wgottschalk Yeah, sounds like a great idea! Would you mind PRing that?

**Comment by ductiletoaster** [comment]
I've been build out a workflow CLI for my company and ran into an issue with some of the typings. In retrospect I probably should have created a new ticket but I created this PR to help solve my issue.
https://github.com/infinitered/gluegun/pull/564

I apologies again for hijacking this thread. Please let me know if you'd like me to create a new ticket.
