### ISSUE TITLE
Dead link in the documentation

### ISSUE THREAD

**Issue by mikeerickson** [infinitered/gluegun#417]
There is a link in the docs which points to your Movie CLI example

https://infinitered.github.io/gluegun/#/?id=welcome-to-gluegun

points to 

https://github.com/infinitered/tutorial-movie

**Comment by cmckni3** [comment]
Looks it was under @jamonholmgren's account as [gluegun-movies-demo](https://github.com/jamonholmgren/gluegun-movies-demo). It's a bit outdated though

**Comment by cmckni3** [comment]
I suggest moving it to infinitered/gluegun-movies-tutorial or similar. Then refreshing it with 2.0 changes of gluegun.

Thoughts @jamonholmgren

**Comment by kevinvangelder** [comment]
This was resolved this morning. Thanks for reporting!
