### ISSUE TITLE
Typescript Inconsistencies

### ISSUE THREAD

**Issue by RichiCoder1** [infinitered/gluegun#418]
Was referred to this (excellent) library by a coworker and ran into a few small issues while building out a typescript.

Biggest one was passing `GluegunCommand` a generic paramter with a customized `Toolbox` (for inbox helpers, etc) results in losing typings on all the `Gluegun` in-built helpers as the exported `Toolbox` type which you'd inherit from has a quirk that kills all types for the implements base. I'm pretty sure this is easy to fix though, and will submit a PR. `Toolbox` is also missing some typings.

It may also be work generating a `{{appName}}-types.d.ts` with an `export interface {{appName}}Toolbox extends Toolbox` and `export declare {{appName}}Command = GluegunCommand<{{appName}Toolbox>` for the typescript template as a starting point for peeps who might want to type helpers.

**Comment by jamonholmgren** [comment]
I would love having a better generated typescript boilerplate. Good work on this!
