### ISSUE TITLE
API design questions

### ISSUE THREAD

**Issue by yordis** [infinitered/gluegun#429]
I see that you could do

```js
 const { system, print, filesystem, strings } = toolbox
```

To be honest, I haven't used this style at all, I prefer to import these things from `gluegun` itself.

```js
import { system, print, filesystem, strings } from 'gluegun'
```

I don't know why this API decision was made and I am pretty sure you have your reasons to do so, but I am curious about this.

Especially that the type systems love static analysis and dealing with runtime mutations are really hard to maintain in terms of typing.

I know that Gluegun has the capability of extensions which I don't understand why you would need to mutate the `toolbox` itself instead of simply import the extension as any other JS module.

Now doing this 

```js
  .plugins('node_modules', { matching: 'movie-*' })
```

I see the useful use case of loading more commands at runtime, but the packages itself do not need `extensions` itself but the ability to enable commands at runtime.

So, 

I am curious about this 🤔

**Comment by jamonholmgren** [comment]
@yordis Thanks for the question! Steve Kellock made that decision early on and isn't involved with the project anymore, so I'm not privy to his reasons. I do know that using the provided toolbox is helpful because you can easily create a fake toolbox for testing reasons. But either way is acceptable to do -- use what you prefer. Note that you can also use them directly, like this:

```js
import { system } from 'gluegun/system'
import { print } from 'gluegun/print'
import { filesystem } from 'gluegun/filesystem'
import { strings } from 'gluegun/strings'
```

**Comment by yordis** [comment]
@jamonholmgren why would you encourage people to use `extensions` then?

It makes things confusing and hard, the only tradeoff is saving extra imports 😄 

>  I do know that using the provided toolbox is helpful because you can easily create a fake toolbox for testing reasons.

Interesting.

**Comment by jamonholmgren** [comment]
@yordis I like extensions, myself, but you don't have to use them. For example, AWS Amplify CLI uses them like this: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/src/extensions/amplify.js

**Comment by yordis** [comment]
I get that, that is why I like the idea of mutating the context but without doing that much magic. What I dislike from the current implementation is that everything is explicit and introduces too many questions.

The rabbit hole on this is expecting **other plugins** to mutate your context so you can use specific functionality. If people are not disciplined, this could become an issue.

If you find yourself relying on contexts that you do not control on your library, probably the best solution is to import the functionality explicit rather than implicit and then people can't figure out where things are coming from.

For example, I am doing this right now.

```ts
import { IStrawHatConfig } from '../environment';

export interface IStrawHatToolbox extends Toolbox {
  strawHat: {
    config: IStrawHatConfig;
  };
}

export interface IStrawHatCommand extends GluegunCommand<IStrawHatToolbox> {
  env: Environments;
}

export function createCommand(
  command: IStrawHatCommand
): GluegunCommand<IStrawHatToolbox> {
  return {
    ...command,
    async run(toolbox) {
      print.info(`Running on CI: ${print.colors.success(isCI)}`);
      setupEnv(command.env);

      toolbox.strawHat = {
        config: strawHatConfigFactory({
          env: command.env,
        }),
      };

      await command.run(toolbox as IStrawHatToolbox);
    },
  };
}
```

Do I extend the context?

Yes, I do, but you are explicit on doing. When you call `createCommand` you can figure out who is inject things into your context.

For example, an issue with this API design is avoiding a naming conflict.

How do you know that some random extension will no break another extension by using the same context key or something like that?

The only solution will be to be aware of your plugins/extensions, but the more flexible and popular something become, the harder will be to do this.

### Note

I am not trying to bash here, these are feedbacks from using Gluegun and getting burned out so many times in my career. 

Every implementation has ups and downs, and I am just trying to figure out if how to improve Gluegun.
