### ISSUE TITLE
gitignore file lists lock files

### ISSUE THREAD

**Issue by BoyWithSilverWings** [infinitered/gluegun#430]
The [.gitignore](https://github.com/infinitered/gluegun/blob/master/src/cli/templates/cli/.gitignore.ejs#L6) file lists down `package.lock.json` and `yarn.lock.json`.

As shown in the npm docs, this is a file that should be committed. 

Is there a reason for this?

**Comment by jamonholmgren** [comment]
Hey @BoyWithSilverWings ! You're right, we should commit one of those files. Since we use Yarn at Infinite Red, I'd prefer that.

Would you want to submit a PR to fix the .gitignore?
