### ISSUE TITLE
It's possible to configure a custom template renderer?

### ISSUE THREAD

**Issue by httpiago** [infinitered/gluegun#431]
Let's say I wanted to use [boring](https://github.com/mjstahl/boring) instead of ejs

**Comment by jamonholmgren** [comment]
Hey @httpiago! Yeah, that's definitely possible to do. I would create your own extension and manipulate the toolbox, like this:

```typescript
module.exports = async (toolbox: GluegunToolbox) => {
  const generate: GluegunTemplate = (opts: Options = {}): Promise<string> => {
    // use boring here, but keep the same API
  }
  toolbox.template = { generate }
}
```

Look at the [current implementation](https://github.com/infinitered/gluegun/blob/da07b53ab8dfb08b23c5c89fb94e3688ebdd9c11/src/core-extensions/template-extension.ts) for ideas, if you want.
