### ISSUE TITLE
Update enquirer version to use new types

### ISSUE THREAD

**Issue by tmadison-gpsw** [infinitered/gluegun#441]
Getting this error when trying to use enquirer select/multiselect type.

`Error: prompt type "select" is not registered` or
`Error: prompt type "multiselect" is not registered`

I believe these are available in 2.0, currently using 1.0.3

**Comment by jamonholmgren** [comment]
Hey @tmadison-gpsw ! I tried upgrading to enquirer 2.0 but unfortunately this is a nontrivial task, since they significantly broke backwards compatibility. If you want to try doing it I'd be very appreciative. In the meantime, you can use `checkbox` and `radio` to essentially do the same thing.

**Comment by tmadison-gpsw** [comment]
Ok, thanks for the heads up. I will try using `checkbox` and/or `radio`. Closing for now.

**Comment by snowfrogdev** [comment]
I also had the same problem. The examples in Gluegun's docs are using `select` and `multiselect`, it's misleading and it would be better if it only showed types that work.

**Comment by jamonholmgren** [comment]
Should be fixed in #507.
