### ISSUE TITLE
Plugin Samples or Documentation 

### ISSUE THREAD

**Issue by mikeerickson** [infinitered/gluegun#442]
Looking for samples or documentation for creating gluegun plugins. I perused all the information on GitHub repo,  it didn’t have any docs for plugins.

**Comment by jamonholmgren** [comment]
Hey @mikeerickson, was this tutorial not useful to you? 

[Tutorial: Making a Plugin](https://github.com/infinitered/gluegun/blob/master/docs/tutorial-making-a-plugin.md)

If not, what do you think we could do to improve it? I'd love to hear feedback.

**Comment by mikeerickson** [comment]
@jamonholmgren Yep, just found this about 15 minutes ago ;-)  I will peruse this information and let you know if I have any questions/comments.

FYI, we were just talking over break about our direction for our internal CLI framework (aka Ignition) and what we should do moving forward.  Either continue with adding the features we wanted, or move to something like "gluegun" and contribute there with the features we are looking to adopt.  

So, we are going to pause development on our project and move to use gluegun for upcoming projects and see where it takes us.   We will start with enhancing the help system to support "pretty" help as well as our command help integration.

**Comment by jamonholmgren** [comment]
That is fantastic! I know how big of a decision that is, to stop working on something that you've put blood sweat and tears into, and move to someone else's framework. I'm honored you've decided to try Gluegun and really happy to work with you all. Let me know if there's anything you get blocked on and let's see if there's a way to make it as smooth as possible.
