### ISSUE TITLE
How to use typescript in gluegun cli, but still ship it for running on node?

### ISSUE THREAD

**Issue by danludwig** [infinitered/gluegun#451]
Is the only way to do it to have a build process that compiles the ts to js and then ships the js as the cli root (when someone does a `npm i -g` of the cli)? I can't get past the "unexpected token" errors when importing and exporting interfaces.

**Comment by jamonholmgren** [comment]
Hey @danludwig ! We have a build process built-in to the generated Gluegun CLI that you can run with `yarn build`. If you want it to generate TS types, add this to your `tsconfig.json`:

```
    "declaration": true,
    "declarationDir": "build/types",
```

and this to your `package.json`:

```
  "types": "build/types/types.d.ts",
```

Then add a `src/types.ts` file that you export all your public-facing types from.

I may add this to our generated TypeScript CLI, actually.

**Comment by yordis** [comment]
Related to https://github.com/infinitered/gluegun/issues/401

**Comment by yordis** [comment]
I think this could be related to https://github.com/infinitered/gluegun/issues/401

**Comment by jamonholmgren** [comment]
Tracking the idea of generating public types automatically in #611.
