### ISSUE TITLE
Kitchen sink example in docs not working

### ISSUE THREAD

**Issue by cogoo** [infinitered/gluegun#456]
https://infinitered.github.io/gluegun/#/toolbox-prompt?id=kitchen-sink-example

Issue arises from the `prompt.ask` method. When you pass in an object with type select, the type is not recognised, even though this type is valid when you use enquirer directly

**Comment by jamonholmgren** [comment]
@cogoo Is that the right link? I'm not understanding the relationship to your issue. 😅

**Comment by cogoo** [comment]
Updated the link in the comment

**Comment by jamonholmgren** [comment]
Thanks @cogoo ! Looks like we need to fix the `select` type.

**Comment by cogoo** [comment]
Thanks @jamonholmgren, I can look into this.

**Comment by cogoo** [comment]
It seems like the docs is using the api for Enquirer 3.x, but a few paragraphs above you have this 

> Important: in order to preserve backwards compatibility with Enquirer 1.x, we translate type: 'list' to type: 'select'. If you want to use the new list behavior, please use enquirer directly and not through Gluegun.

So we can change the kitchen sink example to use the correct types where applicable or allow the full api of enquirer through gluegun?

**Comment by jamonholmgren** [comment]
Should be fixed in #507 (cc @cogoo) and Gluegun 3.2.1.
