### ISSUE TITLE
Which Language Would You Like to Use? prompt should not accept invalid input

### ISSUE THREAD

**Issue by sw-yx** [infinitered/gluegun#457]
Currently running gluegun shows this:
![image](https://user-images.githubusercontent.com/6764957/52912079-7c8e8c00-3250-11e9-8f42-2d7d2b31de78.png)

and when i type "Typescript" instead of "TypeScript" it runs a JS build instead.

expected behavior: it should allow us to pick from a limited set of options instead of relying on user entry.

i looked around the issues and couldnt believe nobody's raised this before. seems a simple dx thing to fix?

**Comment by jamonholmgren** [comment]
This is strange, it's supposed to display a language picker here! Marked as a bug so we can look into this.

**Comment by rdewolff** [comment]
This does not work at all for me.

**Comment by rdewolff** [comment]
added an issue to track the global error : https://github.com/infinitered/gluegun/issues/462

**Comment by jamonholmgren** [comment]
Fixed in #465.
