### ISSUE TITLE
Refactor command & extension loading

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#46]
These files are pretty much copy & paste of each other:

* https://github.com/skellock/gluegun/blob/master/packages/gluegun/src/loaders/command-loader.js
* https://github.com/skellock/gluegun/blob/master/packages/gluegun/src/loaders/extension-loader.js

Do the right thing.

**Comment by abrophy** [comment]
Dug down into this and you're absolutely write. With minor changes ,that don't effect anything outside of the plugin loader, all tests pass with command-loader serving as a complete replacement to extension-loader.

My question is: which name for the loader better describes the purpose it serves, or would you like to use another name entirely for the loader that serves both purposes?

**Comment by skellock** [comment]
Good question.

What are commands & extensions known as?  They're both already horribly generically named already.  haha.

I don't really want to invent a new term either.

Maybe something like `loadable.js`?

I dunno, what do you think?

**Comment by skellock** [comment]
BTW:  don't feel like you need to do maintenance stuff like this.  Usually people like doing features cuz that's fun!

Thank you btw for your contributions!  This library is really generic and it's nice to see people getting some value out of it.

**Comment by abrophy** [comment]
Was just tackling some low hanging fruit as a warm up today.

I'm glad to be helpful, and hope to keep ramping up and taking on meatier stuff!
