### ISSUE TITLE
importing types failing 

### ISSUE THREAD

**Issue by GantMan** [infinitered/gluegun#460]
In Solidarity I'm using Gluegun 3.0 in a branch.  I'm unable to bring in types where you use `import`

This results in the following 2 lines in `filesyste-types.d.ts` causing a typescript compile error.

![image](https://user-images.githubusercontent.com/997157/53259280-5162cd00-3694-11e9-84f9-288c68f58ca4.png)

Once this is fixed, I can move solidarity to 3.0 and it can go back to canary testing.

**Comment by jamonholmgren** [comment]
@GantMan I'm having trouble replicating this. Your `fix_tests` branch seems to be building no problem.

![image](https://user-images.githubusercontent.com/1479215/53772085-f7cf7f00-3e99-11e9-9f57-76d989669dde.png)

**Comment by jamonholmgren** [comment]
Going to close for now; feel free to re-open if it's still an issue.
