### ISSUE TITLE
`build` script doesn't copy templates directory and files to build folder

### ISSUE THREAD

**Issue by snowfrogdev** [infinitered/gluegun#509]
So I have used the gluegun cli to create a new cli project and built myself an nice little cli. It works just fine on my machine in dev mode. But when I published it to npm and installed it globally on my other machine, I noticed a problem with the templates. It would give me a template not found error.

 I went back to look at what was generated in the build folder when running the `build` script and realized that it didn't copy the templates into it. I added them manually to the build folder and republished to npm. Reinstalled on my other machine and now it works.

Clearly, the built code expects to find the templates in the build folder but the `build` script doesn't seem to copy them in there. How can I fix this?

Here is the repo: https://github.com/snowfrogdev/Vts
You can install the npm package: npm i -g vts-cli

**Comment by jamonholmgren** [comment]
@snowfrogdev Ah, interesting! (Thanks for using Gluegun btw.) I'm at React Finland right now, but will take a look at this soon. In the meantime, if you find a way to fix it, a PR would be awesome.

**Comment by jamonholmgren** [comment]
I've created a pull request on your repo to fix this issue @snowfrogdev. I'll also update the Gluegun template. 👍
