### ISSUE TITLE
checkForUpdates is not a function

### ISSUE THREAD

**Issue by joebochill** [infinitered/gluegun#581]
I'm reading through the tutorials, and so far i'm really liking the tool, but I ran into a snag trying to get ```checkForUpdates``` (https://infinitered.github.io/gluegun/#/runtime?id=checkforupdates) to work.

Typescript complains that 'checkForUpdates does not exist on type Builder' and sure enough, a global search of the gluegun node_modules folder reveals that it's not defined anywhere in the package.

Am i missing something, or was this functionality recently removed?

gluegun version: 3.3.3
node version: 10.16.0

<img width="530" alt="Screen Shot 2019-08-17 at 9 39 31 AM" src="https://user-images.githubusercontent.com/29152776/63212461-efc76c80-c0d2-11e9-85ac-5bf16dee3a06.png">

**Comment by jamonholmgren** [comment]
Hey @joebochill ! Sorry about the delay.

It is defined here: https://github.com/infinitered/gluegun/blob/2160bb47515ec85ff273ba14d2523e893614c4d8/src/domain/builder.ts#L153-L156

Maybe check your Gluegun version? It was added [in 3.3.0](https://github.com/infinitered/gluegun/pull/531).

**Comment by jamonholmgren** [comment]
Wait, you said your version is 3.3.3. That's very odd.

**Comment by jamonholmgren** [comment]
I added Gluegun and it does seem to be in the build?

![image](https://user-images.githubusercontent.com/1479215/64069198-da396300-cbf9-11e9-8ffc-eb11e9c728ca.png)

**Comment by jamonholmgren** [comment]
I'm also seeing it in TypeScript:

![image](https://user-images.githubusercontent.com/1479215/64069212-1bca0e00-cbfa-11e9-86c1-4e7509a1a5d8.png)

**Comment by joebochill** [comment]
I figured out why it's not there... I have the gluegun CLI installed globally @3.3.3, but when I use it to create a project, it's using ^2.1.0 (for JavaScript and TypeScript projects). I'm not sure if that's intended and I'm just meant to update it in my project, or if that's a bug in the CLI.

**Comment by jamonholmgren** [comment]
@joebochill Yikes, that's a bug for sure. Would you mind submitting a PR?

**Comment by joebochill** [comment]
I'm on it. Should be able to have something tomorrow.
