### ISSUE TITLE
Support default commands

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#60]
Currently a command can't live on it's own.  It needs to live under a namespace.

With `spork`, i made that name space.  And since namespaces aren't commands, you can't just type it.  So I created `default` as the command.

So now it's:

`gluegun spork default`

Which is lame.

I want:

`gluegun spork`.

So we need to build the concept of a default command.  `default.js` would be fine, but I think `index.js` is a little nicer because of the convention on the web and React Native.

**Comment by jamonholmgren** [comment]
Agree, and FWIW I'd prefer `default.js`.

**Comment by skellock** [comment]
Bumping again.  @GantMan needs this for `ignite-source-map`.

I don't know why I'm bumping.

**Comment by GantMan** [comment]
+1
