### ISSUE TITLE
Extract toolbox

### ISSUE THREAD

**Issue by yordis** [infinitered/gluegun#627]
As today,

Gluegun had done an amazing job, I couldn't love more the toolbox object and have everything handy without worry about putting together so many tools.

But, when it comes to the commands I would like to use https://github.com/oclif/oclif

Could we split extract gluegun out to an independent package?

I found myself literally copying almost everything from gluegun and I wouldn't like to maintain my own code when so many smart people are maintaining this package.

**Comment by jamonholmgren** [comment]
You can already! Just do this:

```
yarn add gluegun
```

```javascript
import { filesystem, print } from "gluegun"
```

Or you can import them from each individual place:

```javascript
import { filesystem } from "gluegun/filesystem"
```

Might be a good thing to document better somewhere.

**Comment by yordis** [comment]
True true 🤦🏻‍♂️

Let me think about this, ideally, the other pieces of the software don't affect me ... hopefully.

**Comment by jamonholmgren** [comment]
@yordis Would you want to help document this?

**Comment by yordis** [comment]
@jamonholmgren could you assign it to me so I have it in my todo tasks from GitHub? Otherwise, I will forget about this

**Comment by jamonholmgren** [comment]
I think this is documented well enough for now, so I'm closing this.
