### ISSUE TITLE
Question: Upgrading gluegun from v2 to v4

### ISSUE THREAD

**Issue by cmburcus** [infinitered/gluegun#679]
Hi,

First and foremost, thank you for all the amazing work done! I am loving everything about this tool!

I started playing around with gluegun a while back when it was in version 2. Back then there was no option for typescript. I want to upgrade my version to the latest (4.1.1) and I wanted to know if there is some sort of guide to do so?

I know in theory it shouldn't be that hard but I'm trying to avoid having to create a new cli and porting my files over. If there is no guide, if anyone has done this have any pointers for what's the easiest way to go about it, it would be greatly appreciated.

Thank you!

**Comment by jamonholmgren** [comment]
Hey @cmburcus! Thanks so much for the kind words, you made my day. 😀 

You should be able to upgrade to 4.1.2 without much in the way of problems. Give it a go and see what happens. Gluegun 1-2 was a bigger change than 2-4.

3.0 changelog: https://github.com/infinitered/gluegun/releases/tag/v3.0.0
4.0 changelog: https://github.com/infinitered/gluegun/releases/tag/v4.0.0

If you want to enable TypeScript, take a look at [the current template](https://github.com/infinitered/gluegun/tree/bbd1b1485716c0a168b479a99e35dec1f614a049/src/cli/templates/cli) and see how we set it up. Look especially in the root folder. For the most part, you shouldn't have to change much in the commands themselves.

**Comment by cmburcus** [comment]
Thank you for your answer @jamonholmgren ! I'll give it a go :) I'll re-post if I need any help. Really excited to start using typescript with gluegun!
