### ISSUE TITLE
quick start running program - not found

### ISSUE THREAD

**Issue by markfirmware** [infinitered/gluegun#730]
using gitpod ... following quick start ... typescript and name is ingest ... ingest does not work

    gitpod /workspace/test33/ingest $ yarn link
    yarn link v1.22.10
    success Registered "ingest".
    info You can now run `yarn link "ingest"` in the projects where you want to use this package and it will be used instead.
    Done in 0.04s.
     gitpod /workspace/test33/ingest $ ingest
    bash: ingest: command not found

**Comment by montera82** [comment]
how was this fixed? facing same issue!
