### ISSUE TITLE
Typescript warnings because of `NodeJS.EventEmitter`

### ISSUE THREAD

**Issue by mikenikles** [infinitered/gluegun#740]
I recently upgraded `@types/node` to `16.11.11` and started to notice the following two errors.

<details>
  <summary>Expand to see logs</summary>
  <pre>
gitpod /workspace/webstone/packages/cli $ pnpm prepublishOnly

> @webstone/cli@0.7.0 prepublishOnly /workspace/webstone/packages/cli
> pnpm build

> @webstone/cli@0.7.0 build /workspace/webstone/packages/cli
> pnpm clean && pnpm compile && pnpm copy-templates

> @webstone/cli@0.7.0 clean /workspace/webstone/packages/cli
> rm -rf ./dist

> @webstone/cli@0.7.0 compile /workspace/webstone/packages/cli
> tsc -p .

../../node_modules/.pnpm/gluegun@4.7.0/node_modules/gluegun/build/types/toolbox/prompt-enquirer-types.d.ts:70:34 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

70 declare class BasePrompt extends NodeJS.EventEmitter {
                                    ~~~~~~

../../node_modules/.pnpm/gluegun@4.7.0/node_modules/gluegun/build/types/toolbox/prompt-enquirer-types.d.ts:75:44 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

75 declare class Enquirer<T = object> extends NodeJS.EventEmitter {
  </pre>
</details>

A fix that works in my environment, but I'd need a maintainer's input on this, is to remove `extends NodeJS.EventEmitter` from [here](https://github.com/infinitered/gluegun/blob/master/src/toolbox/prompt-enquirer-types.ts#L99) and [here](https://github.com/infinitered/gluegun/blob/master/src/toolbox/prompt-enquirer-types.ts#L107).

FWIW, I found the Commander folks ended up with [the same fix for their project](https://github.com/tj/commander.js/pull/1146/files).

**Comment by jamonholmgren** [comment]
@mikenikles Do you know if we can just remove the `extends NodeJS.EventEmitter` or do we also need to add the `on()` method signature like the Commander folks did?

**Comment by Cahllagerfeld** [comment]
I think it's related to `@types/node` which still works when installing `v12.*`, but not anymore with the current version of the node-types from `v16.*`, right? @mikenikles
