### ISSUE TITLE
Unable to import build module from gluegun

### ISSUE THREAD

**Issue by Niraj-Kamdar** [infinitered/gluegun#744]
# Steps to reproduce:
- create a new node project with gluegun installed
- create a simple js file that imports `build` from `gluegun`
- Run this file

## simple.js
```js
var { build } = require("gluegun");
``` 
## package.json
```json
{
  "name": "playground",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "gluegun": "4.7.1"
  }
}
```

**Comment by Niraj-Kamdar** [comment]
Nevermind it's due to this: https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

I would recommend downgrading the dependency `colors` to a sane version

**Comment by mkucmus** [comment]
> Nevermind it's due to this: https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/
> 
> I would recommend downgrading the dependency `colors` to a sane version

Great move! Thousands of projects wait for that fix! 💪🏻
