### ISSUE TITLE
toolbox.prompt overwrites all items

### ISSUE THREAD

**Issue by imranMnts** [infinitered/gluegun#753]
**Describe the bug**
`toolbox.prompt.ask` overwrites all items

**To Reproduce**

Issue :
```
let addNewItem = true;
const result = [];
while (addNewItem) {
  const item = await toolbox.prompt.ask({
      type: 'input',
      name: `name`,
      message: `message`,
  });

  result.push(item);
  addNewItem = await toolbox.prompt.confirm('continue?');
}
console.log('result: ', result);
```

the first time, we put `1` as name input, and `2` the second time

**Result**

print: 
```result:  [ { name: '2', yesno: false }, { name: '2', yesno: false } ]```

**Expected behavior**
print: 
```result:  [ { name: '1' }, { name: '2' } ]```

**Doctor (please complete the following information):**
 - OS: 11.6.2
 - Gluegun Version: 5.1.0

**Comment by jamonholmgren** [comment]
@imranMnts Thanks for the bug report. Would you mind taking a shot at a PR?

**Comment by jamonholmgren** [comment]
This would be a good opportunity for a regression test as well.

**Comment by imranMnts** [comment]
@jamonholmgren I created this PR https://github.com/infinitered/gluegun/pull/754

can you please have a look?

**Comment by imranMnts** [comment]
@jamonholmgren 

Can we have an update, please?

**Comment by ugur-eren** [comment]
I guess you can also use destructuring assignment to get the name as seen on the [docs](https://infinitered.github.io/gluegun/#/toolbox-prompt?id=ask), while waiting for Jamon's thoughts about this. So you would avoid passing the object reference to the array.

```javascript
const {name} = await toolbox.prompt.ask({
    type: 'input',
    name: `name`,
    message: `message`,
});

result.push({name});
```
Or, if you're using `ask` with an array to ask many questions at once, you can use spread syntax to get all responses.

```javascript
const {...item} = await toolbox.prompt.ask({
    type: 'input',
    name: `name`,
    message: `message`,
});

result.push({...item});
```
