### ISSUE TITLE
Temporary directory

### ISSUE THREAD

**Issue by ElonVolo** [infinitered/gluegun#756]
**Note that Gluegun is community-supported and the core team will not be adding new features other than those submitted as PRs by the community.**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. Gluegun doesn't work very well when [...]

I think it would be useful for gluegun's filesystem  toolbox item to include functionality for creating directories (maybe temporary files to, but at least temporary directories to start with)

**Describe the solution you'd like**

Expose fs-jetpack's tmpDir to the filesystem toolbox.

**Describe alternatives you've considered**

While there's several differently approaches that could be taken (separately import/require fs-jetpack, using node.js fs.mkdtempSync, etc) it would be nice to have a handy shortcut to not have to look up those api's and have something that leverages the toolbox approaches consistent interface. The advantage of using gluegun in general is avoiding the "crap, I have to look this up again across a zillion modules' documentations" problem.

**Additional context**

**Comment by jamonholmgren** [comment]
Good idea. I’ll review and merge a PR to this effect!

**Comment by ElonVolo** [comment]
It turns out the functionality should already be available in the most current fs-jetpack, it's just that the version of fs-jetpack is about two years old, and when I bumped up the version of fs-jetpack to 4.3.1 the API call appeared.
