### ISSUE TITLE
documentation site is broken

### ISSUE THREAD

**Issue by cellog** [infinitered/gluegun#772]
**Describe the bug**
The documentation site for gluegun fails to load because the console reports that `Prism` is not found.

**To Reproduce**
1. go to https://infinitered.github.io/gluegun/

**Expected behavior**
it loads

**Screenshots**
![Screen Shot 2023-01-11 at 12 28 26 PM](https://user-images.githubusercontent.com/98250/211876197-77f22e16-ea29-48ca-a4bc-c184045fb98f.png)

**Doctor (please complete the following information):**

**Additional context**

**Comment by jamonholmgren** [comment]
Looks like it's working!
